import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import ts from "typescript";

const root = process.cwd();
const sourcePath = path.join(root, "extensions", "workflows", "workflow-source-shape.ts");
const outputPath = path.join(root, "dist", "workflow-source-shape.mjs");
const source = await readFile(sourcePath, "utf8");
const result = ts.transpileModule(source, {
  fileName: sourcePath,
  compilerOptions: {
    module: ts.ModuleKind.ES2022,
    target: ts.ScriptTarget.ES2022,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    newLine: ts.NewLineKind.LineFeed,
    removeComments: false,
  },
  reportDiagnostics: true,
});
const errors = result.diagnostics?.filter((diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error) ?? [];
if (errors.length > 0) {
  throw new Error(
    ts.formatDiagnostics(errors, {
      getCanonicalFileName: (fileName) => fileName,
      getCurrentDirectory: () => root,
      getNewLine: () => "\n",
    }),
  );
}

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by scripts/build-workflow-source-shape.ts. Do not edit.\n${result.outputText}`,
);
